version: "3.5"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 --port 9000 -t

